CREATE TABLE IF NOT EXISTS cadunico (
    id BIGSERIAL PRIMARY KEY,
    cpf_cnpj TEXT NOT NULL UNIQUE,
    inscricao_estadual TEXT,
    inscricao_municipal TEXT,
    fantasia TEXT NOT NULL,
    inss TEXT,
    crea TEXT,
    email TEXT,
    telefones TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    aniversario DATE,
    id_estrangeiro TEXT,
    codigo_pais TEXT,
    cep TEXT NOT NULL,
    endereco TEXT NOT NULL,
    numero TEXT,
    complemento TEXT,
    bairro TEXT NOT NULL,
    cidade TEXT NOT NULL,
    uf TEXT NOT NULL,
    codigo_ibge TEXT NOT NULL,
    enviar_nfe BOOLEAN NOT NULL DEFAULT FALSE,
    enviar_boleto BOOLEAN NOT NULL DEFAULT FALSE,
    enviar_extrato BOOLEAN NOT NULL DEFAULT FALSE,
    etiqueta BOOLEAN NOT NULL DEFAULT FALSE,
    comissao BOOLEAN NOT NULL DEFAULT FALSE,
    construcao_civil BOOLEAN NOT NULL DEFAULT FALSE,
    cep_cobranca TEXT,
    endereco_cobranca TEXT,
    numero_cobranca TEXT,
    complemento_cobranca TEXT,
    bairro_cobranca TEXT,
    cidade_cobranca TEXT,
    uf_cobranca TEXT,
    codigo_ibge_cobranca TEXT,
    referencia_cobranca TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
